#ifndef _EEPROM_ADDRESSES_H_
#define _EEPROM_ADDRESSES_H_

#include "occupancy.h"

// EEPROM Location Definitions


#define EE_OCC_ADDR_BASE    0x10
#define EE_OCC_PKT_BASE     0x20
#define EE_OCC_BITBYTE_BASE 0x30
#define EE_OCC_SUBTYPE_BASE 0x40

#define EE_E_APRCH_ADDR       (EE_OCC_ADDR_BASE + OCC_E_APRCH)
#define EE_E_APRCH2_ADDR      (EE_OCC_ADDR_BASE + OCC_E_APRCH2)
#define EE_E_ADJ_ADDR         (EE_OCC_ADDR_BASE + OCC_E_ADJ)
#define EE_E_OS_ADDR          (EE_OCC_ADDR_BASE + OCC_E_OS)
#define EE_E_TUMBLE_ADDR      (EE_OCC_ADDR_BASE + OCC_E_TUMBLE)
#define EE_W_APRCH_ADDR       (EE_OCC_ADDR_BASE + OCC_W_APRCH)
#define EE_W_APRCH2_ADDR      (EE_OCC_ADDR_BASE + OCC_W_APRCH2)
#define EE_W_ADJ_ADDR         (EE_OCC_ADDR_BASE + OCC_W_ADJ)
#define EE_W_OS_ADDR          (EE_OCC_ADDR_BASE + OCC_W_OS)
#define EE_W_TUMBLE_ADDR      (EE_OCC_ADDR_BASE + OCC_W_TUMBLE)
#define EE_MAIN_ADDR          (EE_OCC_ADDR_BASE + OCC_MAIN)
#define EE_SIDING_ADDR        (EE_OCC_ADDR_BASE + OCC_SIDE)

#define EE_E_APRCH_PKT        (EE_OCC_PKT_BASE + OCC_E_APRCH)
#define EE_E_APRCH2_PKT       (EE_OCC_PKT_BASE + OCC_E_APRCH2)
#define EE_E_ADJ_PKT          (EE_OCC_PKT_BASE + OCC_E_ADJ)
#define EE_E_OS_PKT           (EE_OCC_PKT_BASE + OCC_E_OS)
#define EE_E_TUMBLE_PKT       (EE_OCC_PKT_BASE + OCC_E_TUMBLE)
#define EE_W_APRCH_PKT        (EE_OCC_PKT_BASE + OCC_W_APRCH)
#define EE_W_APRCH2_PKT       (EE_OCC_PKT_BASE + OCC_W_APRCH2)
#define EE_W_ADJ_PKT          (EE_OCC_PKT_BASE + OCC_W_ADJ)
#define EE_W_OS_PKT           (EE_OCC_PKT_BASE + OCC_W_OS)
#define EE_W_TUMBLE_PKT       (EE_OCC_PKT_BASE + OCC_W_TUMBLE)
#define EE_MAIN_PKT           (EE_OCC_PKT_BASE + OCC_MAIN)
#define EE_SIDING_PKT         (EE_OCC_PKT_BASE + OCC_SIDE)

#define EE_E_APRCH_BITBYTE    (EE_OCC_BITBYTE_BASE + OCC_E_APRCH)
#define EE_E_APRCH2_BITBYTE   (EE_OCC_BITBYTE_BASE + OCC_E_APRCH2)
#define EE_E_ADJ_BITBYTE      (EE_OCC_BITBYTE_BASE + OCC_E_ADJ)
#define EE_E_OS_BITBYTE       (EE_OCC_BITBYTE_BASE + OCC_E_OS)
#define EE_E_TUMBLE_BITBYTE   (EE_OCC_BITBYTE_BASE + OCC_E_TUMBLE)
#define EE_W_APRCH_BITBYTE    (EE_OCC_BITBYTE_BASE + OCC_W_APRCH)
#define EE_W_APRCH2_BITBYTE   (EE_OCC_BITBYTE_BASE + OCC_W_APRCH2)
#define EE_W_ADJ_BITBYTE      (EE_OCC_BITBYTE_BASE + OCC_W_ADJ)
#define EE_W_OS_BITBYTE       (EE_OCC_BITBYTE_BASE + OCC_W_OS)
#define EE_W_TUMBLE_BITBYTE   (EE_OCC_BITBYTE_BASE + OCC_W_TUMBLE)
#define EE_MAIN_BITBYTE       (EE_OCC_BITBYTE_BASE + OCC_MAIN)
#define EE_SIDING_BITBYTE     (EE_OCC_BITBYTE_BASE + OCC_SIDE)

#define EE_E_APRCH_SUBTYPE    (EE_OCC_SUBTYPE_BASE + OCC_E_APRCH)
#define EE_E_APRCH2_SUBTYPE   (EE_OCC_SUBTYPE_BASE + OCC_E_APRCH2)
#define EE_E_ADJ_SUBTYPE      (EE_OCC_SUBTYPE_BASE + OCC_E_ADJ)
#define EE_E_OS_SUBTYPE       (EE_OCC_SUBTYPE_BASE + OCC_E_OS)
#define EE_E_TUMBLE_SUBTYPE   (EE_OCC_SUBTYPE_BASE + OCC_E_TUMBLE)
#define EE_W_APRCH_SUBTYPE    (EE_OCC_SUBTYPE_BASE + OCC_W_APRCH)
#define EE_W_APRCH2_SUBTYPE   (EE_OCC_SUBTYPE_BASE + OCC_W_APRCH2)
#define EE_W_ADJ_SUBTYPE      (EE_OCC_SUBTYPE_BASE + OCC_W_ADJ)
#define EE_W_OS_SUBTYPE       (EE_OCC_SUBTYPE_BASE + OCC_W_OS)
#define EE_W_TUMBLE_SUBTYPE   (EE_OCC_SUBTYPE_BASE + OCC_W_TUMBLE)
#define EE_MAIN_SUBTYPE       (EE_OCC_SUBTYPE_BASE + OCC_MAIN)
#define EE_SIDING_SUBTYPE     (EE_OCC_SUBTYPE_BASE + OCC_SIDE)


#endif
